name: .NET

on:
  push:
    branches: [master, dev, ravencoin-rollback]
  pull_request:
    branches: [master, dev, ravencoin-rollback]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [debian-11, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Install Build dependencies
      run: |
        if [ ${{ matrix.os }} == 'debian-11' ]; then
          sudo apt-get install -y cmake build-essential libssl-dev pkg-config libboost-all-dev libsodium-dev libzmq5
        fi
        if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
          # Install the required dependencies for Ubuntu
          # Modify this section as needed for Ubuntu dependencies
          sudo apt-get install -y your-ubuntu-dependencies-here
        fi
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --no-restore src
    - name: Test
      run: dotnet test --logger:"console;verbosity=detailed" --no-build --verbosity normal src
